name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.22.0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.6.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      - name: Get kubeconfig
        run: aws eks update-kubeconfig --name your-eks-cluster --region your-region

      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install my-app ./helm/my-app --set image.repository=${{ secrets.DOCKER_USERNAME }}/my-app --set image.tag=latest --namespace default --create-namespace
